# Gradle properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.38.0
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.38.0

org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.configuration-cache.parallel=true

benManesPluginId=io.github.ben-manes.versions
benManesPluginVersion=0.57.0