####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./gradlew build -Dquarkus.native.enabled=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/tuarkus .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/tuarkus
#
# The `registry.access.redhat.com/ubi10/ubi-minimal:10.2-1782798957` base image is based on UBI 10.
# The tag pins both the 10.2 release and its exact build for reproducibility.
###
FROM registry.access.redhat.com/ubi10/ubi-minimal:10.2-1782798957
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --chmod=0755 build/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
